[options]
# true colors
enable_guicolors = true

# filetype icon
enable_tabline_filetype_icon = true

# indent
default_indent = 4

# do not expand tabs
expand_tab = true

# set end column line
max_column = 81

# cursor
enable_cursorline = true
enable_cursorcolumn = true

# filetree
filetree_direction = "left"

# autocomplete
autocomplete_method = "coc"

# absolute numbering
relativenumber = false

# hide file tree
enable_vimfiler_welcome = false

# bootstrap
bootstrap_after = 'myspacevim#after'

########################################
# layers

# disable smooth scrolling
[[layers]]
name = 'core'
enable_smooth_scrolling = false

[[layers]]
name = "autocomplete"
auto_completion_return_key_behavior = "complete"

[[layers]]
name = 'fzf'

[[layers]]
name = 'cscope'

[[layers]]
name = 'git'
git_plugin = 'fugitive'

[[layers]]
name = 'VersionControl'

[[layers]]
name = "lsp"
filetypes = [
	"c",
	"rust"
]
[layers.override_cmd]
    c = ["ccls"]
########################################

########################################
# lang
[[layers]]
name = "lang#c"
format_on_save = true

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#sh"
########################################
